# docker-compose.yml
version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nextjsdb
    ports:
      - "5432:5432"
    volumes:
      - E:/developer/DockerData/postgres:/var/lib/postgresql/data
volumes:
  postgres_data: